'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ru' | 'en' | 'ky';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ru: {
    // Общие
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.add': 'Добавить',
    'common.search': 'Поиск',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    
    // Навигация
    'nav.dashboard': 'Панель управления',
    'nav.courses': 'Курсы',
    'nav.lessons': 'Уроки',
    'nav.students': 'Ученики',
    'nav.employees': 'Сотрудники',
    'nav.applications': 'Заявки',
    'nav.payments': 'Платежи',
    'nav.reviews': 'Отзывы',
    'nav.alumni': 'Выпускники',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    
    // Дашборд
    'dashboard.title': 'Панель управления',
    'dashboard.overview': 'Обзор',
    'dashboard.stats': 'Статистика',
    'dashboard.analytics': 'Аналитика',
    
    // Курсы
    'courses.title': 'Управление курсами',
    'courses.add': 'Добавить курс',
    'courses.name': 'Название курса',
    'courses.description': 'Описание',
    'courses.duration': 'Длительность',
    'courses.price': 'Стоимость',
    'courses.status': 'Статус',
    
    // Сотрудники
    'employees.title': 'Сотрудники',
    'employees.add': 'Добавить сотрудника',
    'employees.name': 'Имя',
    'employees.position': 'Должность',
    'employees.email': 'Email',
    'employees.phone': 'Телефон',
    
    // Авторизация
    'auth.signin': 'Вход',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.code': 'Код подтверждения',
    'auth.getCode': 'Получить код',
    'auth.verify': 'Войти',
    'auth.logout': 'Выйти',
    'auth.adminPanel': 'Панель администратора',
    'auth.sendingCode': 'Отправка кода...',
    'auth.checking': 'Проверка...',
    'auth.twoFactor': 'Двухфакторная аутентификация',
    'auth.codeSent': 'Код отправлен в Telegram для',
    'auth.sixDigitCode': '6-значный код',
    'auth.protected': 'Защищено двухфакторной аутентификацией через Telegram',
    'auth.loginError': 'Ошибка входа',
    'auth.wrongCode': 'Неверный код',
    'auth.generalError': 'Произошла ошибка',
    'auth.emailPlaceholder': 'admin@email.com',
    'auth.passwordPlaceholder': 'Введите пароль',
    'auth.codePlaceholder': '000000',
    'auth.tokenNotReceived': 'Токен не получен от сервера',
    
    // Расширенные общие
    'common.create': 'Создать',
    'common.all': 'Все',
    'common.total': 'Всего',
    'common.active': 'Активен',
    'common.inactive': 'Неактивен',
    'common.activeOnSite': 'Активен на сайте',
    'common.status': 'Статус',
    'common.actions': 'Действия',
    'common.back': 'Назад',
    'common.confirm': 'Подтвердить',
    'common.reject': 'Отклонить',
    'common.publish': 'Опубликовать',
    'common.change': 'Изменить',
    'common.remove': 'Удалить',
    'common.apply': 'Применить',
    'common.saving': 'Сохранение...',
    'common.reset': 'Сбросить',
    'common.notSpecified': 'Не указан',
    'common.noName': 'Без имени',
    'common.noDescription': 'Нет описания',
    'common.notFound': 'Не найдено',
    
    // Расширенная навигация
    'nav.siteStats': 'Статистика',
    'nav.adminPanel': 'Admin Panel',
    
    // Расширенный дашборд
    'dashboard.welcome': 'Добро пожаловать в систему управления ОКУРМЭН',
    'dashboard.totalCourses': 'Всего курсов',
    'dashboard.students': 'Студентов',
    'dashboard.revenue': 'Доход',
    'dashboard.pendingApplications': 'Заявки',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.addCourse': 'Добавить курс',
    'dashboard.addEmployee': 'Добавить сотрудника',
    'dashboard.viewApplications': 'Просмотреть заявки',
    'dashboard.som': 'сом',
    
    // Расширенные курсы
    'courses.management': 'Управление курсами',
    'courses.totalActive': 'Всего: {total} курсов • Активных: {active}',
    'courses.createCourse': 'Создать курс',
    'courses.searchPlaceholder': 'Поиск курсов по названию или описанию...',
    'courses.notFound': 'Курсы не найдены',
    'courses.createFirst': 'Создайте первый курс, чтобы начать работу',
    'courses.popular': 'Популярный',
    'courses.noTitle': 'Без названия',
    'courses.noDescription': 'Нет описания',
    'courses.hours': 'часов',
    'courses.noLessons': 'Нет уроков',
    'courses.period': 'Период',
    'courses.som': 'сом',
    'courses.editCourse': 'Редактировать курс',
    'courses.createNew': 'Создать новый курс',
    'courses.autoCalculation': 'Автоматические расчеты',
    'courses.ratingFromReviews': 'Рейтинг рассчитывается из отзывов курса',
    'courses.studentsFromEnrollments': 'Количество студентов — из активных записей',
    'courses.hoursFromLessons': 'Длительность в часах — из опубликованных уроков',
    'courses.titleRequired': 'Название курса *',
    'courses.slugRequired': 'Slug (URL) *',
    'courses.priceRequired': 'Цена (сом) *',
    'courses.durationPeriod': 'Длительность (период обучения)',
    'courses.format': 'Формат',
    'courses.level': 'Уровень',
    'courses.online': 'Онлайн',
    'courses.offline': 'Оффлайн',
    'courses.hybrid': 'Гибрид',
    'courses.beginner': 'Начальный',
    'courses.intermediate': 'Средний',
    'courses.advanced': 'Продвинутый',
    'courses.cover': 'Обложка курса',
    'courses.gradientIcon': 'Градиент + Иконка',
    'courses.uploadPhoto': 'Загрузить фото',
    'courses.selectIcon': 'Выберите иконку:',
    'courses.saveChanges': 'Сохранить изменения',
    'courses.confirmDelete': 'Вы уверены, что хотите удалить этот курс?',
    
    // Сотрудники (расширенное)
    'employees.totalCount': 'Всего: {count} сотрудников',
    'employees.searchPlaceholder': 'Поиск по имени, должности, email...',
    'employees.notFoundFiltered': 'Сотрудники не найдены по заданным критериям',
    'employees.notFound': 'Сотрудники отсутствуют',
    'employees.experience': 'Опыт в ОКУРМЭН',
    'employees.noName': 'Без имени',
    'employees.loadError': 'Ошибка загрузки сотрудников',
    'employees.deleteSuccess': 'Сотрудник {name} успешно удалён',
    'employees.deleteError': 'Ошибка при удалении сотрудника',
    'employees.editEmployee': 'Редактировать сотрудника',
    'employees.addEmployee': 'Добавить сотрудника',
    'employees.fullNameRequired': 'ФИО *',
    'employees.positionsRequired': 'Должности * (выберите одну или несколько)',
    'employees.education': 'Образование',
    'employees.okurmenTitle': 'Сотрудники ОКУРМЭН',
    'employees.positionNotSpecified': 'Должность не указана',
    'employees.confirmDelete': 'Вы уверены, что хотите удалить сотрудника "{name}"?',
    'employees.saveSuccess': 'Сотрудник "{name}" сохранён!',
    'employees.createSuccess': 'Сотрудник "{name}" добавлен!',
    'employees.updateSuccess': 'Сотрудник "{name}" обновлён!',
    'employees.saveError': 'Ошибка: {message}',
    'employees.serverError': 'Ошибка сервера: {status} {statusText}',
    'employees.savingError': 'Ошибка при сохранении',
    'employees.selectPositions': 'Выберите хотя бы одну должность',
    'employees.bioPlaceholder': 'Краткая информация о сотруднике',
    'employees.photoLabel': 'Фото сотрудника',
    'employees.photoHint': 'Портретное фото 3:4. Изображение будет автоматически обрезано и оптимизировано для карточки.',
    'employees.fullNameLabel': 'ФИО *',
    'employees.positionsLabel': 'Должности * (выберите одну или несколько)',
    'employees.emailLabel': 'Email',
    'employees.phoneLabel': 'Телефон',
    'employees.experienceLabel': 'Опыт в ОКУРМЭН',
    'employees.educationLabel': 'Образование',
    'employees.bioLabel': 'Биография / Описание',
    'employees.fullNamePlaceholder': 'Иван Иванов',
    'employees.emailPlaceholder': 'email@email.com',
    'employees.phonePlaceholder': '+996 XXX XXX XXX',
    'employees.experiencePlaceholder': '1 год 3 месяца',
    'employees.educationPlaceholder': 'Высшее образование',
    
    // Должности
    'position.founder': 'Основатель',
    'position.director': 'Руководитель/Директор',
    'position.headTeacher': 'Завуч',
    'position.departmentHead': 'Руководитель отдела',
    'position.rop': 'РОП',
    'position.seniorManager': 'Старший менеджер',
    'position.manager': 'Менеджер',
    'position.curator': 'Куратор',
    'position.mentor': 'Ментор',
    'position.teacher': 'Преподаватель',
    'position.developer': 'Разработчик',
    'position.hr': 'HR',
    'position.marketing': 'Маркетолог',
    'position.smm': 'SMM',
    'position.sales': 'Продажи',
    'position.adminStaff': 'Административный персонал',
    'position.other': 'Другое',
    
    // Департаменты
    'department.all': 'Все сотрудники',
    'department.leadership': 'Руководство',
    'department.mentoring': 'Менторинг',
    'department.salesManagement': 'Продажи и Управление',
    'department.studio': 'ОКУРМЭН Студия',
    
    // Студенты
    'students.title': 'Ученики и Группы',
    'students.totalInGroups': 'Всего: {total} учеников в {groups} группах',
    'students.createGroup': 'Создать группу',
    'students.noGroups': 'Группы отсутствуют',
    'students.group': 'Группа',
    'students.studentsCount': '{count} ученик/ов',
    'students.statusActive': 'Учится',
    'students.statusInactive': 'Неактивен',
    'students.statusGraduated': 'Завершил',
    'students.statusDropped': 'Отчислен',
    'students.dateNotSpecified': 'Не указана',
    'students.startDate': 'Начало:',
    'students.endDate': 'Окончание:',
    'students.editGroup': 'Редактировать группу',
    'students.groupName': 'Название группы *',
    'students.mentor': 'Ментор группы',
    'students.noMentor': '-- Без ментора --',
    'students.groupActive': 'Группа активна',
    'students.addToGroup': 'Добавить ученика в группу',
    'students.fullNameRequired': 'ФИО ученика *',
    'students.groupPrefix': 'Группа',
    'students.studentCount': '{count} ученик/ов',
    'students.grantAccess': 'Выдать доступ к курсу',
    'students.grantAccessStudent': 'Выдать доступ к курсу',
    'students.selectMentor': 'Выберите ментора для группы (опционально)',
    'students.groupDeleteSuccess': 'Группа "{name}" удалена',
    'students.deleteStudentError': 'Ошибка при удалении ученика',
    'students.saveSuccess': 'Группа "{name}" {action}',
    'students.groupCreated': 'создана',
    'students.groupUpdated': 'обновлена',
    'students.studentAddSuccess': 'Ученик "{name}" добавлен в группу {group}',
    'students.addError': 'Ошибка: {message}',
    'students.addStudentError': 'Не удалось добавить ученика',
    'students.selectCourseError': 'Пожалуйста, выберите курс',
    'students.selectCourseLabel': 'Выберите курс *',
    'students.selectCoursePlaceholder': '-- Выберите курс --',
    'students.grantAccessWarning': 'Доступ будет выдан всем {count} ученикам группы',
    'students.courseLabel': 'Курс:',
    'students.studentsLabel': 'учеников',
    'students.confirmDeleteGroup': 'Удалить группу "{name}"?',
    
    // Уроки
    'lessons.title': 'Уроки',
    'lessons.management': 'Управление уроками в курсах',
    'lessons.addLesson': 'Добавить урок',
    'lessons.searchPlaceholder': 'Поиск по названию или описанию',
    'lessons.allCourses': 'Все курсы',
    'lessons.notFound': 'Уроки не найдены',
    'lessons.noTitle': 'Без названия',
    'lessons.course': 'Курс:',
    'lessons.courseNotSpecified': 'Курс не указан',
    'lessons.noDescription': 'Нет описания',
    'lessons.video': 'Видео',
    'lessons.content': 'Контент',
    'lessons.editLesson': 'Редактировать урок',
    'lessons.createLesson': 'Создать урок',
    'lessons.selectCourse': 'Выберите курс',
    'lessons.lessonTitle': 'Название урока',
    'lessons.order': 'Порядок',
    'lessons.videoUrl': 'URL видео',
    'lessons.lessonContent': 'Контент урока',
    'lessons.durationPlaceholder': '45 минут',
    'lessons.videoUrlPlaceholder': 'https://youtube.com/...',
    'lessons.contentPlaceholder': 'Markdown контент урока...',
    
    // Выпускники
    'alumni.title': 'Выпускники',
    'alumni.subtitle': 'Успешные истории наших студентов',
    'alumni.addAlumni': 'Добавить выпускника',
    'alumni.searchPlaceholder': 'Поиск по имени, компании или должности',
    'alumni.notFound': 'Выпускники не найдены',
    'alumni.projects': 'Проекты:',
    
    // Заявки
    'applications.title': 'Заявки на курсы',
    'applications.subtitle': 'Управление заявками студентов',
    'applications.searchPlaceholder': 'Поиск по имени, email или телефону',
    'applications.allStatuses': 'Все статусы',
    'applications.statusPending': 'В ожидании',
    'applications.statusContacted': 'Связались',
    'applications.statusConfirmed': 'Подтверждены',
    'applications.statusRejected': 'Отклонены',
    'applications.statusCancelled': 'Отменены',
    'applications.notFound': 'Заявки не найдены',
    'applications.noEmail': 'Нет email',
    'applications.noPhone': 'Нет телефона',
    'applications.course': 'Курс:',
    
    // Отзывы
    'reviews.title': 'Отзывы',
    'reviews.subtitle': 'Управление отзывами студентов',
    'reviews.searchPlaceholder': 'Поиск по имени, отзыву или курсу',
    'reviews.allStatuses': 'Все статусы',
    'reviews.statusPending': 'На модерации',
    'reviews.statusPublished': 'Опубликовано',
    'reviews.statusRejected': 'Отклонено',
    'reviews.notFound': 'Отзывы не найдены',
    'reviews.anonymous': 'Аноним',
    'reviews.noEmail': 'Нет email',
    'reviews.noText': 'Нет текста отзыва',
    
    // Настройки
    'settings.title': 'Настройки',
    'settings.subtitle': 'Управление настройками системы',
    'settings.general': 'Общие',
    'settings.profile': 'Профиль',
    'settings.notifications': 'Уведомления',
    'settings.security': 'Безопасность',
    'settings.theme': 'Тема',
    'settings.lightMode': 'Светлый режим',
    'settings.darkMode': 'Тёмный режим',
    'settings.changeTheme': 'Изменить тему отображения',
    'settings.language': 'Язык',
    'settings.sectionInDevelopment': 'Этот раздел в разработке',
    
    // Статистика сайта
    'siteStats.title': 'Статистика сайта',
    'siteStats.subtitle': 'Управление статистикой, отображаемой на главной странице',
    'siteStats.totalStudents': 'Общее количество студентов',
    'siteStats.displayedAs': 'На главной странице отобразится:',
    'siteStats.employmentRate': 'Процент трудоустройства',
    
    // ImageUploader
    'imageUploader.fileTooLarge': 'Файл слишком большой! Максимум {maxSizeMB}MB',
    'imageUploader.pleaseSelectImage': 'Пожалуйста, выберите изображение',
    'imageUploader.change': 'Изменить',
    'imageUploader.clickToSelect': 'Нажмите для выбора изображения',
    'imageUploader.square': 'Квадрат 1:1',
    'imageUploader.wide': 'Широкий 16:9',
    'imageUploader.portrait': 'Портрет 3:4',
    'imageUploader.standard': 'Стандарт 4:3',
    'imageUploader.editImage': 'Редактировать изображение',
    'imageUploader.dragScale': 'Перетащите, масштабируйте и поверните изображение',
    'imageUploader.dragHint': '💡 Зажми и тяни изображение чтобы переместить',
    'imageUploader.rotate90': 'Повернуть 90°',
    'imageUploader.reset': 'Сбросить',
    
    // Ошибки
    'error.updateApplicationStatus': 'Ошибка при обновлении статуса заявки: {error}',
    'error.updateApplicationStatusGeneric': 'Ошибка при обновлении статуса заявки',
    'error.apiConnection': 'Не удалось подключиться к API. Проверьте подключение к интернету.',
    
    // Страница статистики
    'statistics.title': 'Управление статистикой',
    'statistics.subtitle': 'Настройте период и показатели для отображения на сайте',
    'statistics.save': 'Сохранить',
    'statistics.saving': 'Сохранение...',
    'statistics.saveSuccess': '✅ Настройки сохранены',
    'statistics.saveError': '❌ Ошибка сохранения',
    'statistics.siteStatsTitle': 'Статистика главной страницы',
    'statistics.siteStatsDescription': 'Эти данные отображаются на главной странице сайта',
    'statistics.saveSiteStats': 'Сохранить статистику сайта',
    'statistics.savingSiteStats': 'Сохранение...',
    'statistics.periodTitle': 'Период',
    'statistics.periodType': 'Тип периода',
    'statistics.periodMonth': 'За месяц',
    'statistics.periodYear': 'За год',
    'statistics.periodAllTime': 'За всё время',
    'statistics.month': 'Месяц',
    'statistics.year': 'Год',
    'statistics.publishTitle': 'Публикация',
    'statistics.publishCheckbox': 'Отображать статистику на сайте',
    'statistics.metricsTitle': 'Показатели за период',
    'statistics.metricsDescription': 'Эти показатели считаются за выбранный период',
    'statistics.currentMetricsTitle': 'Текущие показатели',
    'statistics.currentMetricsDescription': 'Эти показатели не зависят от периода',
    'statistics.metricValue': 'Значение: {value}',
    'statistics.monthJanuary': 'Январь',
    'statistics.monthFebruary': 'Февраль',
    'statistics.monthMarch': 'Март',
    'statistics.monthApril': 'Апрель',
    'statistics.monthMay': 'Май',
    'statistics.monthJune': 'Июнь',
    'statistics.monthJuly': 'Июль',
    'statistics.monthAugust': 'Август',
    'statistics.monthSeptember': 'Сентябрь',
    'statistics.monthOctober': 'Октябрь',
    'statistics.monthNovember': 'Ноябрь',
    'statistics.monthDecember': 'Декабрь',
    'statistics.metricNewStudents': 'Новые студенты',
    'statistics.metricNewStudentsDesc': 'Количество новых студентов за период',
    'statistics.metricNewApplications': 'Новые заявки',
    'statistics.metricNewApplicationsDesc': 'Количество новых заявок за период',
    'statistics.metricCompletedApplications': 'Завершённые заявки',
    'statistics.metricCompletedApplicationsDesc': 'Количество подтверждённых заявок',
    'statistics.metricNewPayments': 'Новые оплаты',
    'statistics.metricNewPaymentsDesc': 'Количество новых оплат за период',
    'statistics.metricTotalPaymentAmount': 'Сумма оплат (сом)',
    'statistics.metricTotalPaymentAmountDesc': 'Общая сумма оплат за период',
    'statistics.metricNewReviews': 'Новые отзывы',
    'statistics.metricNewReviewsDesc': 'Количество новых отзывов',
    'statistics.metricNewBookings': 'Новые бронирования',
    'statistics.metricNewBookingsDesc': 'Количество новых бронирований',
    'statistics.metricTotalStudents': 'Всего студентов',
    'statistics.metricTotalStudentsDesc': 'Текущее количество студентов',
    'statistics.metricActiveStudents': 'Активные студенты',
    'statistics.metricActiveStudentsDesc': 'Количество активных студентов',
    'statistics.metricTotalCourses': 'Всего курсов',
    'statistics.metricTotalCoursesDesc': 'Текущее количество курсов',
    'statistics.metricActiveCourses': 'Активные курсы',
    'statistics.metricActiveCoursesDesc': 'Количество активных курсов',
    'statistics.metricTotalEmployees': 'Всего сотрудников',
    'statistics.metricTotalEmployeesDesc': 'Текущее количество сотрудников',
    'statistics.metricActiveEmployees': 'Активные сотрудники',
    'statistics.metricActiveEmployeesDesc': 'Количество активных сотрудников',
    'statistics.metricTotalGroups': 'Всего групп',
    'statistics.metricTotalGroupsDesc': 'Текущее количество групп',
    'statistics.metricTotalLessons': 'Всего уроков',
    'statistics.metricTotalLessonsDesc': 'Текущее количество уроков',
    'statistics.metricTotalAlumni': 'Выпускники',
    'statistics.metricTotalAlumniDesc': 'Количество выпускников',
    
    // Дашборд
    'dashboard.totalCoursesLabel': 'Всего курсов',
    'dashboard.applicationsLabel': 'Заявки',
    'dashboard.revenueLabel': 'Доход',
    'dashboard.quickActionsTitle': 'Быстрые действия',
    'dashboard.addCourseButton': 'Добавить курс',
    'dashboard.addEmployeeButton': 'Добавить сотрудника',
    'dashboard.viewApplicationsButton': 'Просмотреть заявки',
    'dashboard.courseNotSpecified': 'Курс не указан',
    
    // Загрузка и ошибки
    'common.loadingEllipsis': 'Загрузка...',
    'error.loadingError': 'Ошибка загрузки',
    'error.pleaseReload': 'Пожалуйста, перезагрузите страницу',
    'common.reload': 'Перезагрузить',
    
    // Сообщения студентов
    'students.errorLoadingGroups': '❌ Ошибка загрузки групп',
    'students.studentRemovedFromGroup': '✅ "{name}" удалён из группы',
    'students.errorRemovingStudent': '❌ Ошибка удаления студента',
    'students.groupDeletedSuccess': '✅ Группа "{name}" успешно удалена',
    'students.errorDeletingGroup': '❌ Ошибка при удалении группы',
    'students.confirmDeleteStudent': 'Удалить "{name}" из группы?',
    'students.confirmDeleteGroupMessage': 'Вы уверены, что хотите удалить группу "{name}"?',
    'students.noGroupsFound': 'Группы отсутствуют',
    'students.noStudentsInGroup': 'В группе пока нет учеников',
    'students.addFirstStudent': 'Добавить первого ученика',
    'students.editGroupTooltip': 'Редактировать группу',
    'students.deleteGroupTooltip': 'Удалить группу',
    'students.addStudentTooltip': 'Добавить ученика',
    'students.grantAccessTooltip': 'Открыть доступ к курсу',
    'students.grantAccessButton': 'Открыть доступ к курсу',
    'students.deleteStudentTooltip': 'Удалить из группы',
    'students.editGroupTitle': 'Редактировать группу {name}',
    'students.createGroupTitle': 'Создать группу',
    'students.groupNameLabel': 'Название группы *',
    'students.mentorLabel': 'Ментор группы',
    'students.noMentorOption': '-- Без ментора --',
    'students.mentorHint': 'Выберите ментора для группы (необязательно)',
    'students.descriptionLabel': 'Описание',
    'students.descriptionPlaceholder': 'Опишите группу...',
    'students.startDateLabel': 'Дата начала',
    'students.endDateLabel': 'Дата окончания',
    'students.groupActiveLabel': 'Группа активна',
    'students.groupUpdatedSuccess': '✅ Группа "{name}" обновлена',
    'students.groupCreatedSuccess': '✅ Группа "{name}" создана',
    'students.saveErrorGeneric': 'Ошибка: Не удалось сохранить группу',
    'students.loadingMentors': 'Загрузка менторов...',
  },
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.courses': 'Courses',
    'nav.lessons': 'Lessons',
    'nav.students': 'Students',
    'nav.employees': 'Employees',
    'nav.applications': 'Applications',
    'nav.payments': 'Payments',
    'nav.reviews': 'Reviews',
    'nav.alumni': 'Alumni',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.stats': 'Statistics',
    'dashboard.analytics': 'Analytics',
    
    // Courses
    'courses.title': 'Course Management',
    'courses.add': 'Add Course',
    'courses.name': 'Course Name',
    'courses.description': 'Description',
    'courses.duration': 'Duration',
    'courses.price': 'Price',
    'courses.status': 'Status',
    
    // Employees
    'employees.title': 'Employees',
    'employees.add': 'Add Employee',
    'employees.name': 'Name',
    'employees.position': 'Position',
    'employees.email': 'Email',
    'employees.phone': 'Phone',
    
    // Auth
    'auth.signin': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.code': 'Verification Code',
    'auth.getCode': 'Get Code',
    'auth.verify': 'Sign In',
    'auth.logout': 'Logout',
    'auth.adminPanel': 'Admin Panel',
    'auth.sendingCode': 'Sending code...',
    'auth.checking': 'Checking...',
    'auth.twoFactor': 'Two-Factor Authentication',
    'auth.codeSent': 'Code sent to Telegram for',
    'auth.sixDigitCode': '6-digit code',
    'auth.protected': 'Protected by two-factor authentication via Telegram',
    'auth.loginError': 'Login error',
    'auth.wrongCode': 'Invalid code',
    'auth.generalError': 'An error occurred',
    'auth.emailPlaceholder': 'admin@email.com',
    'auth.passwordPlaceholder': 'Enter password',
    'auth.codePlaceholder': '000000',
    'auth.tokenNotReceived': 'Token not received from server',
    
    // Common (дополнительные)
    'common.create': 'Create',
    'common.all': 'All',
    'common.total': 'Total',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.activeOnSite': 'Active on site',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.reject': 'Reject',
    'common.publish': 'Publish',
    'common.change': 'Change',
    'common.remove': 'Remove',
    'common.apply': 'Apply',
    'common.saving': 'Saving...',
    'common.reset': 'Reset',
    'common.notSpecified': 'Not specified',
    'common.noName': 'No name',
    'common.noDescription': 'No description',
    'common.notFound': 'Not found',
    'common.checkConnection': 'Check your connection',
    
    // Extended navigation
    'nav.siteStats': 'Statistics',
    'nav.adminPanel': 'Admin Panel',
    
    // Extended dashboard
    'dashboard.welcome': 'Welcome to OKURMEN management system',
    'dashboard.totalCourses': 'Total Courses',
    'dashboard.students': 'Students',
    'dashboard.revenue': 'Revenue',
    'dashboard.pendingApplications': 'Applications',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addCourse': 'Add Course',
    'dashboard.addEmployee': 'Add Employee',
    'dashboard.viewApplications': 'View Applications',
    'dashboard.som': 'som',
    
    // Extended courses
    'courses.management': 'Course Management',
    'courses.totalActive': 'Total: {total} courses • Active: {active}',
    'courses.createCourse': 'Create Course',
    'courses.searchPlaceholder': 'Search courses by title or description...',
    'courses.notFound': 'No courses found',
    'courses.createFirst': 'Create your first course to get started',
    'courses.popular': 'Popular',
    'courses.noTitle': 'Untitled',
    'courses.noDescription': 'No description',
    'courses.hours': 'hours',
    'courses.noLessons': 'No lessons',
    'courses.period': 'Period',
    'courses.som': 'som',
    'courses.editCourse': 'Edit Course',
    'courses.createNew': 'Create New Course',
    'courses.autoCalculation': 'Automatic Calculations',
    'courses.ratingFromReviews': 'Rating is calculated from course reviews',
    'courses.studentsFromEnrollments': 'Number of students from active enrollments',
    'courses.hoursFromLessons': 'Duration in hours from published lessons',
    'courses.titleRequired': 'Course Title *',
    'courses.slugRequired': 'Slug (URL) *',
    'courses.priceRequired': 'Price (som) *',
    'courses.durationPeriod': 'Duration (study period)',
    'courses.format': 'Format',
    'courses.level': 'Level',
    'courses.online': 'Online',
    'courses.offline': 'Offline',
    'courses.hybrid': 'Hybrid',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.cover': 'Course Cover',
    'courses.gradientIcon': 'Gradient + Icon',
    'courses.uploadPhoto': 'Upload Photo',
    'courses.selectIcon': 'Select icon:',
    'courses.saveChanges': 'Save Changes',
    'courses.confirmDelete': 'Are you sure you want to delete this course?',
    'courses.hoursCount': '{hours} hours',
    'courses.noLessonsCount': 'No lessons',
    'courses.durationPlaceholder': '6 months',
    'courses.durationHint': 'Total duration in hours is calculated automatically from lessons',
    'courses.saveError': 'Error: {message}',
    'courses.savingError': 'Error saving course',
    'courses.activeCount': 'Active',
    
    // Extended employees
    'employees.totalCount': 'Total: {count} employees',
    'employees.searchPlaceholder': 'Search by name, position, email...',
    'employees.notFoundFiltered': 'No employees found matching the criteria',
    'employees.notFound': 'No employees found',
    'employees.experience': 'Experience at OKURMEN',
    'employees.noName': 'No name',
    'employees.loadError': 'Error loading employees',
    'employees.deleteSuccess': 'Employee {name} deleted successfully',
    'employees.deleteError': 'Error deleting employee',
    'employees.editEmployee': 'Edit Employee',
    'employees.addEmployee': 'Add Employee',
    'employees.fullNameRequired': 'Full Name *',
    'employees.positionsRequired': 'Positions * (select one or more)',
    'employees.education': 'Education',
    'employees.okurmenTitle': 'OKURMEN Employees',
    'employees.positionNotSpecified': 'Position not specified',
    'employees.confirmDelete': 'Are you sure you want to delete employee "{name}"?',
    'employees.saveSuccess': 'Employee "{name}" saved successfully!',
    'employees.createSuccess': 'Employee "{name}" added successfully!',
    'employees.updateSuccess': 'Employee "{name}" updated successfully!',
    'employees.saveError': 'Error: {message}',
    'employees.serverError': 'Server error: {status} {statusText}',
    'employees.savingError': 'Error saving employee',
    'employees.selectPositions': 'Select at least one position',
    'employees.bioPlaceholder': 'Brief information about the employee',
    'employees.photoLabel': 'Employee Photo',
    'employees.photoHint': 'Portrait photo 3:4. Image will be automatically cropped and optimized for employee cards.',
    'employees.fullNameLabel': 'Full Name *',
    'employees.positionsLabel': 'Positions * (select one or more)',
    'employees.emailLabel': 'Email',
    'employees.phoneLabel': 'Phone',
    'employees.experienceLabel': 'Experience at OKURMEN',
    'employees.educationLabel': 'Education',
    'employees.bioLabel': 'Bio / Description',
    'employees.fullNamePlaceholder': 'John Doe',
    'employees.emailPlaceholder': 'email@email.com',
    'employees.phonePlaceholder': '+996 XXX XXX XXX',
    'employees.experiencePlaceholder': '1 year 3 months',
    'employees.educationPlaceholder': 'Higher education',
    
    // Positions
    'position.founder': 'Founder',
    'position.director': 'Director',
    'position.headTeacher': 'Head Teacher',
    'position.departmentHead': 'Department Head',
    'position.rop': 'ROP',
    'position.seniorManager': 'Senior Manager',
    'position.manager': 'Manager',
    'position.curator': 'Curator',
    'position.mentor': 'Mentor',
    'position.teacher': 'Teacher',
    'position.developer': 'Developer',
    'position.hr': 'HR',
    'position.marketing': 'Marketing',
    'position.smm': 'SMM',
    'position.sales': 'Sales',
    'position.adminStaff': 'Administrative Staff',
    'position.other': 'Other',
    
    // Departments
    'department.all': 'All Employees',
    'department.leadership': 'Leadership',
    'department.mentoring': 'Mentoring',
    'department.salesManagement': 'Sales & Management',
    'department.studio': 'OKURMEN Studio',
    
    // Students
    'students.title': 'Students and Groups',
    'students.totalInGroups': 'Total: {total} students in {groups} groups',
    'students.createGroup': 'Create Group',
    'students.noGroups': 'No groups found',
    'students.group': 'Group',
    'students.studentsCount': '{count} student(s)',
    'students.statusActive': 'Active',
    'students.statusInactive': 'Inactive',
    'students.statusGraduated': 'Graduated',
    'students.statusDropped': 'Dropped',
    'students.dateNotSpecified': 'Not specified',
    'students.startDate': 'Start:',
    'students.endDate': 'End:',
    'students.editGroup': 'Edit Group',
    'students.groupName': 'Group Name *',
    'students.mentor': 'Group Mentor',
    'students.noMentor': '-- No Mentor --',
    'students.groupActive': 'Group is active',
    'students.addToGroup': 'Add Student to Group',
    'students.fullNameRequired': 'Student Full Name *',
    'students.groupPrefix': 'Group',
    'students.studentCount': '{count} student(s)',
    'students.confirmDeleteGroup': 'Delete group "{name}"?',
    'students.grantAccess': 'Grant Course Access',
    'students.grantAccessStudent': 'Grant course access',
    'students.selectMentor': 'Select a mentor for the group (optional)',
    'students.groupDeleteSuccess': 'Group "{name}" deleted successfully',
    'students.deleteStudentError': 'Error deleting student',
    'students.saveSuccess': 'Group "{name}" {action}',
    'students.groupCreated': 'created',
    'students.groupUpdated': 'updated',
    'students.studentAddSuccess': 'Student "{name}" added to group {group}',
    'students.addError': 'Error: {message}',
    'students.addStudentError': 'Failed to add student',
    'students.selectCourseError': 'Please select a course',
    'students.selectCourseLabel': 'Select Course *',
    'students.selectCoursePlaceholder': '-- Select a course --',
    'students.grantAccessWarning': 'Access will be granted to all {count} students in the group',
    'students.courseLabel': 'Course:',
    'students.studentsLabel': 'students',
    
    // Lessons
    'lessons.title': 'Lessons',
    'lessons.management': 'Course Lessons Management',
    'lessons.addLesson': 'Add Lesson',
    'lessons.searchPlaceholder': 'Search by title or description',
    'lessons.allCourses': 'All Courses',
    'lessons.notFound': 'No lessons found',
    'lessons.noTitle': 'Untitled',
    'lessons.course': 'Course:',
    'lessons.courseNotSpecified': 'Course not specified',
    'lessons.noDescription': 'No description',
    'lessons.video': 'Video',
    'lessons.content': 'Content',
    'lessons.editLesson': 'Edit Lesson',
    'lessons.createLesson': 'Create Lesson',
    'lessons.selectCourse': 'Select Course',
    'lessons.lessonTitle': 'Lesson Title',
    'lessons.order': 'Order',
    'lessons.videoUrl': 'Video URL',
    'lessons.lessonContent': 'Lesson Content',
    'lessons.durationPlaceholder': '45 minutes',
    'lessons.videoUrlPlaceholder': 'https://youtube.com/...',
    'lessons.contentPlaceholder': 'Markdown lesson content...',
    'lessons.confirmDelete': 'Are you sure you want to delete this lesson?',
    
    // Alumni
    'alumni.title': 'Alumni',
    'alumni.subtitle': 'Success stories of our students',
    'alumni.addAlumni': 'Add Alumni',
    'alumni.searchPlaceholder': 'Search by name, company or position',
    'alumni.notFound': 'No alumni found',
    'alumni.projects': 'Projects:',
    'alumni.confirmDelete': 'Are you sure you want to delete this alumni?',
    
    // Applications
    'applications.title': 'Course Applications',
    'applications.subtitle': 'Student Applications Management',
    'applications.searchPlaceholder': 'Search by name, email or phone',
    'applications.allStatuses': 'All Statuses',
    'applications.statusPending': 'Pending',
    'applications.statusContacted': 'Contacted',
    'applications.statusConfirmed': 'Confirmed',
    'applications.statusRejected': 'Rejected',
    'applications.statusCancelled': 'Cancelled',
    'applications.notFound': 'No applications found',
    'applications.noEmail': 'No email',
    'applications.noPhone': 'No phone',
    'applications.course': 'Course:',
    
    // Reviews
    'reviews.title': 'Reviews',
    'reviews.subtitle': 'Student Reviews Management',
    'reviews.searchPlaceholder': 'Search by name, review or course',
    'reviews.allStatuses': 'All Statuses',
    'reviews.statusPending': 'Pending',
    'reviews.statusPublished': 'Published',
    'reviews.statusRejected': 'Rejected',
    'reviews.notFound': 'No reviews found',
    'reviews.anonymous': 'Anonymous',
    'reviews.noEmail': 'No email',
    'reviews.noText': 'No review text',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'System Settings Management',
    'settings.general': 'General',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.theme': 'Theme',
    'settings.lightMode': 'Light Mode',
    'settings.darkMode': 'Dark Mode',
    'settings.changeTheme': 'Change display theme',
    'settings.language': 'Language',
    'settings.sectionInDevelopment': 'This section is under development',
    
    // Site Stats
    'siteStats.title': 'Site Statistics',
    'siteStats.subtitle': 'Manage statistics displayed on homepage',
    'siteStats.totalStudents': 'Total number of students',
    'siteStats.displayedAs': 'Will be displayed on homepage as:',
    'siteStats.employmentRate': 'Employment rate',
    
    // ImageUploader
    'imageUploader.fileTooLarge': 'File too large! Maximum {maxSizeMB}MB',
    'imageUploader.pleaseSelectImage': 'Please select an image',
    'imageUploader.change': 'Change',
    'imageUploader.clickToSelect': 'Click to select image',
    'imageUploader.square': 'Square 1:1',
    'imageUploader.wide': 'Wide 16:9',
    'imageUploader.portrait': 'Portrait 3:4',
    'imageUploader.standard': 'Standard 4:3',
    'imageUploader.editImage': 'Edit Image',
    'imageUploader.dragScale': 'Drag, scale and rotate image',
    'imageUploader.dragHint': '💡 Drag and move image to reposition',
    'imageUploader.rotate90': 'Rotate 90°',
    'imageUploader.reset': 'Reset',
    
    // Errors
    'error.updateApplicationStatus': 'Error updating application status: {error}',
    'error.updateApplicationStatusGeneric': 'Error updating application status',
    'error.apiConnection': 'Could not connect to API. Please check your internet connection.',
    
    // Statistics Page
    'statistics.title': 'Statistics Management',
    'statistics.subtitle': 'Configure period and metrics for website display',
    'statistics.save': 'Save',
    'statistics.saving': 'Saving...',
    'statistics.saveSuccess': '✅ Settings saved',
    'statistics.saveError': '❌ Save error',
    'statistics.siteStatsTitle': 'Homepage Statistics',
    'statistics.siteStatsDescription': 'This data is displayed on the website homepage',
    'statistics.saveSiteStats': 'Save site statistics',
    'statistics.savingSiteStats': 'Saving...',
    'statistics.periodTitle': 'Period',
    'statistics.periodType': 'Period type',
    'statistics.periodMonth': 'For month',
    'statistics.periodYear': 'For year',
    'statistics.periodAllTime': 'All time',
    'statistics.month': 'Month',
    'statistics.year': 'Year',
    'statistics.publishTitle': 'Publication',
    'statistics.publishCheckbox': 'Display statistics on website',
    'statistics.metricsTitle': 'Period Metrics',
    'statistics.metricsDescription': 'These metrics are calculated for the selected period',
    'statistics.currentMetricsTitle': 'Current Metrics',
    'statistics.currentMetricsDescription': 'These metrics do not depend on period',
    'statistics.metricValue': 'Value: {value}',
    'statistics.monthJanuary': 'January',
    'statistics.monthFebruary': 'February',
    'statistics.monthMarch': 'March',
    'statistics.monthApril': 'April',
    'statistics.monthMay': 'May',
    'statistics.monthJune': 'June',
    'statistics.monthJuly': 'July',
    'statistics.monthAugust': 'August',
    'statistics.monthSeptember': 'September',
    'statistics.monthOctober': 'October',
    'statistics.monthNovember': 'November',
    'statistics.monthDecember': 'December',
    'statistics.metricNewStudents': 'New students',
    'statistics.metricNewStudentsDesc': 'Number of new students in period',
    'statistics.metricNewApplications': 'New applications',
    'statistics.metricNewApplicationsDesc': 'Number of new applications in period',
    'statistics.metricCompletedApplications': 'Completed applications',
    'statistics.metricCompletedApplicationsDesc': 'Number of confirmed applications',
    'statistics.metricNewPayments': 'New payments',
    'statistics.metricNewPaymentsDesc': 'Number of new payments in period',
    'statistics.metricTotalPaymentAmount': 'Payment amount (som)',
    'statistics.metricTotalPaymentAmountDesc': 'Total payment amount in period',
    'statistics.metricNewReviews': 'New reviews',
    'statistics.metricNewReviewsDesc': 'Number of new reviews',
    'statistics.metricNewBookings': 'New bookings',
    'statistics.metricNewBookingsDesc': 'Number of new bookings',
    'statistics.metricTotalStudents': 'Total students',
    'statistics.metricTotalStudentsDesc': 'Current number of students',
    'statistics.metricActiveStudents': 'Active students',
    'statistics.metricActiveStudentsDesc': 'Number of active students',
    'statistics.metricTotalCourses': 'Total courses',
    'statistics.metricTotalCoursesDesc': 'Current number of courses',
    'statistics.metricActiveCourses': 'Active courses',
    'statistics.metricActiveCoursesDesc': 'Number of active courses',
    'statistics.metricTotalEmployees': 'Total employees',
    'statistics.metricTotalEmployeesDesc': 'Current number of employees',
    'statistics.metricActiveEmployees': 'Active employees',
    'statistics.metricActiveEmployeesDesc': 'Number of active employees',
    'statistics.metricTotalGroups': 'Total groups',
    'statistics.metricTotalGroupsDesc': 'Current number of groups',
    'statistics.metricTotalLessons': 'Total lessons',
    'statistics.metricTotalLessonsDesc': 'Current number of lessons',
    'statistics.metricTotalAlumni': 'Alumni',
    'statistics.metricTotalAlumniDesc': 'Number of alumni',
    
    // Dashboard
    'dashboard.totalCoursesLabel': 'Total Courses',
    'dashboard.applicationsLabel': 'Applications',
    'dashboard.revenueLabel': 'Revenue',
    'dashboard.quickActionsTitle': 'Quick Actions',
    'dashboard.addCourseButton': 'Add Course',
    'dashboard.addEmployeeButton': 'Add Employee',
    'dashboard.viewApplicationsButton': 'View Applications',
    'dashboard.courseNotSpecified': 'Course not specified',
    
    // Loading & Error
    'common.loadingEllipsis': 'Loading...',
    'error.loadingError': 'Loading Error',
    'error.pleaseReload': 'Please reload the page',
    'common.reload': 'Reload',
    
    // Students Toast Messages
    'students.errorLoadingGroups': '❌ Error loading groups',
    'students.studentRemovedFromGroup': '✅ "{name}" removed from group',
    'students.errorRemovingStudent': '❌ Error removing student',
    'students.groupDeletedSuccess': '✅ Group "{name}" deleted successfully',
    'students.errorDeletingGroup': '❌ Error deleting group',
    'students.confirmDeleteStudent': 'Remove "{name}" from group?',
    'students.confirmDeleteGroupMessage': 'Are you sure you want to delete group "{name}"?',
    'students.noGroupsFound': 'No groups found',
    'students.noStudentsInGroup': 'No students in group yet',
    'students.addFirstStudent': 'Add first student',
    'students.editGroupTooltip': 'Edit group',
    'students.deleteGroupTooltip': 'Delete group',
    'students.addStudentTooltip': 'Add student',
    'students.grantAccessTooltip': 'Grant course access',
    'students.grantAccessButton': 'Grant access to course',
    'students.deleteStudentTooltip': 'Remove from group',
    'students.editGroupTitle': 'Edit group {name}',
    'students.createGroupTitle': 'Create group',
    'students.groupNameLabel': 'Group name *',
    'students.mentorLabel': 'Group mentor',
    'students.noMentorOption': '-- No mentor --',
    'students.mentorHint': 'Select a mentor for the group (optional)',
    'students.descriptionLabel': 'Description',
    'students.descriptionPlaceholder': 'Describe the group...',
    'students.startDateLabel': 'Start date',
    'students.endDateLabel': 'End date',
    'students.groupActiveLabel': 'Group is active',
    'students.groupUpdatedSuccess': '✅ Group "{name}" updated',
    'students.groupCreatedSuccess': '✅ Group "{name}" created',
    'students.saveErrorGeneric': 'Error: Could not save group',
    'students.loadingMentors': 'Loading mentors...',
  },
  ky: {
    // Жалпы
    'common.save': 'Сактоо',
    'common.cancel': 'Жокко чыгаруу',
    'common.delete': 'Өчүрүү',
    'common.edit': 'Өзгөртүү',
    'common.add': 'Кошуу',
    'common.search': 'Издөө',
    'common.loading': 'Жүктөлүүдө...',
    'common.error': 'Ката',
    'common.success': 'Ийгиликтүү',
    
    // Навигация
    'nav.dashboard': 'Башкы панель',
    'nav.courses': 'Курстар',
    'nav.lessons': 'Сабактар',
    'nav.students': 'Окуучулар',
    'nav.employees': 'Кызматкерлер',
    'nav.applications': 'Арыздар',
    'nav.payments': 'Төлөмдөр',
    'nav.reviews': 'Пикирлер',
    'nav.alumni': 'Бүтүрүүчүлөр',
    'nav.settings': 'Жөндөөлөр',
    'nav.logout': 'Чыгуу',
    
    // Башкы панель
    'dashboard.title': 'Башкы панель',
    'dashboard.overview': 'Жалпы көрүнүш',
    'dashboard.stats': 'Статистика',
    'dashboard.analytics': 'Аналитика',
    
    // Курстар
    'courses.title': 'Курстарды башкаруу',
    'courses.add': 'Курс кошуу',
    'courses.name': 'Курстун аталышы',
    'courses.description': 'Сүрөттөмө',
    'courses.duration': 'Узактыгы',
    'courses.price': 'Баасы',
    'courses.status': 'Статус',
    
    // Кызматкерлер
    'employees.title': 'Кызматкерлер',
    'employees.add': 'Кызматкер кошуу',
    'employees.name': 'Аты',
    'employees.position': 'Кызматы',
    'employees.email': 'Email',
    'employees.phone': 'Телефон',
    
    // Авторизация
    'auth.signin': 'Кируу',
    'auth.email': 'Email',
    'auth.password': 'Сырсөз',
    'auth.code': 'Ырастоо коду',
    'auth.getCode': 'Код алуу',
    'auth.verify': 'Кируу',
    'auth.logout': 'Чыгуу',
    'auth.adminPanel': 'Администратор панели',
    'auth.sendingCode': 'Код жөнөтүлүүдө...',
    'auth.checking': 'Текшерилүүдө...',
    'auth.twoFactor': 'Эки факторлуу аутентификация',
    'auth.codeSent': 'Код Telegramга жөнөтүлдү:',
    'auth.sixDigitCode': '6 сандуу код',
    'auth.protected': 'Telegram аркылуу эки факторлуу аутентификация менен корголгон',
    'auth.loginError': 'Кирүүдө ката',
    'auth.wrongCode': 'Туура эмес код',
    'auth.generalError': 'Ката кетти',
    'auth.emailPlaceholder': 'admin@email.com',
    'auth.passwordPlaceholder': 'Сырсөздү киргизиңиз',
    'auth.codePlaceholder': '000000',
    'auth.tokenNotReceived': 'Сервер токен бере элек',
    
    // Жалпы (кеңейтилген)
    'common.create': 'Түзүү',
    'common.all': 'Бардыгы',
    'common.total': 'Жалпы',
    'common.active': 'Активдүү',
    'common.inactive': 'Активдүү эмес',
    'common.activeOnSite': 'Сайтта активдүү',
    'common.status': 'Статус',
    'common.actions': 'Аракеттер',
    'common.back': 'Артка',
    'common.confirm': 'Ырастоо',
    'common.reject': 'Четке кагуу',
    'common.publish': 'Жарыялоо',
    'common.change': 'Өзгөртүү',
    'common.remove': 'Өчүрүү',
    'common.apply': 'Колдонуу',
    'common.saving': 'Сакталууда...',
    'common.reset': 'Баштапкы абалга келтирүү',
    'common.notSpecified': 'Көрсөтүлгөн эмес',
    'common.noName': 'Аты жок',
    'common.noDescription': 'Сүрөттөмө жок',
    'common.notFound': 'Табылган жок',
    
    // Навигация (кеңейтилген)
    'nav.siteStats': 'Статистика',
    'nav.adminPanel': 'Admin Panel',
    
    // Башкы панель (кеңейтилген)
    'dashboard.welcome': 'ОКУРМЭН башкаруу системасына кош келиңиз',
    'dashboard.totalCourses': 'Жалпы курстар',
    'dashboard.students': 'Окуучулар',
    'dashboard.revenue': 'Киреше',
    'dashboard.pendingApplications': 'Арыздар',
    'dashboard.quickActions': 'Тез аракеттер',
    'dashboard.addCourse': 'Курс кошуу',
    'dashboard.addEmployee': 'Кызматкер кошуу',
    'dashboard.viewApplications': 'Арыздарды көрүү',
    'dashboard.som': 'сом',
    
    // Курсы (кеңейтилген)
    'courses.management': 'Курстарды башкаруу',
    'courses.totalActive': 'Жалпы: {total} курс • Активдүү: {active}',
    'courses.createCourse': 'Курс түзүү',
    'courses.searchPlaceholder': 'Курстарды аталышы же сүрөттөмөсү боюнча издөө...',
    'courses.notFound': 'Курстар табылган жок',
    'courses.createFirst': 'Биринчи курсту түзүп баштаңыз',
    'courses.popular': 'Популярдуу',
    'courses.noTitle': 'Аталышы жок',
    'courses.noDescription': 'Сүрөттөмө жок',
    'courses.hours': 'саат',
    'courses.noLessons': 'Сабактар жок',
    'courses.period': 'Мөөнөт',
    'courses.som': 'сом',
    'courses.editCourse': 'Курсту өзгөртүү',
    'courses.createNew': 'Жаңы курс түзүү',
    'courses.autoCalculation': 'Автоматтык эсептөө',
    'courses.ratingFromReviews': 'Рейтинг курстун пикирлеринен эсептелет',
    'courses.studentsFromEnrollments': 'Окуучулардын саны активдүү жазылуулардан алынат',
    'courses.hoursFromLessons': 'Узактыгы жарыяланган сабактардан эсептелет',
    'courses.titleRequired': 'Курстун аталышы *',
    'courses.slugRequired': 'Slug (URL) *',
    'courses.priceRequired': 'Баасы (сом) *',
    'courses.durationPeriod': 'Узактыгы (окуу мөөнөтү)',
    'courses.format': 'Формат',
    'courses.level': 'Деңгээл',
    'courses.online': 'Онлайн',
    'courses.offline': 'Оффлайн',
    'courses.hybrid': 'Аралаш',
    'courses.beginner': 'Башталгыч',
    'courses.intermediate': 'Орто',
    'courses.advanced': 'Өнүккөн',
    'courses.cover': 'Курстун мукабасы',
    'courses.gradientIcon': 'Градиент + Белги',
    'courses.uploadPhoto': 'Сүрөт жүктөө',
    'courses.selectIcon': 'Белгини тандаңыз:',
    'courses.saveChanges': 'Өзгөрүүлөрдү сактоо',
    'courses.confirmDelete': 'Бул курсту өчүрүүгө ишенесизби?',
    
    // Кызматкерлер (кеңейтилген)
    'employees.totalCount': 'Жалпы: {count} кызматкер',
    'employees.searchPlaceholder': 'Аты, кызматы, email боюнча издөө...',
    'employees.notFoundFiltered': 'Критерийлерге дал келген кызматкерлер табылган жок',
    'employees.notFound': 'Кызматкерлер табылган жок',
    'employees.experience': 'ОКУРМЭНдеги тажрыйба',
    'employees.noName': 'Аты жок',
    'employees.loadError': 'Кызматкерлерди жүктөөдө ката',
    'employees.deleteSuccess': 'Кызматкер {name} ийгиликтүү өчүрүлдү',
    'employees.deleteError': 'Кызматкерди өчүрүүдө ката',
    'employees.editEmployee': 'Кызматкерди өзгөртүү',
    'employees.addEmployee': 'Кызматкер кошуу',
    'employees.fullNameRequired': 'Аты-жөнү *',
    'employees.positionsRequired': 'Кызматтар * (бирөө же бир нечөө тандаңыз)',
    'employees.education': 'Билими',
    'employees.okurmenTitle': 'ОКУРМЭН Кызматкерлери',
    'employees.positionNotSpecified': 'Кызматы көрсөтүлгөн эмес',
    'employees.confirmDelete': 'Кызматкер "{name}" өчүрүүгө ишенесизби?',
    'employees.saveSuccess': 'Кызматкер "{name}" сакталды!',
    'employees.createSuccess': 'Кызматкер "{name}" кошулду!',
    'employees.updateSuccess': 'Кызматкер "{name}" жаңыланды!',
    'employees.saveError': 'Ката: {message}',
    'employees.serverError': 'Сервер катасы: {status} {statusText}',
    'employees.savingError': 'Сактоодо ката',
    'employees.selectPositions': 'Жок дегенде бир кызматты тандаңыз',
    'employees.bioPlaceholder': 'Кызматкер жөнүндө кыска маалымат',
    'employees.photoLabel': 'Кызматкердин сүрөтү',
    'employees.photoHint': 'Портрет сүрөтү 3:4. Сүрөт автоматтык түрдө кесилип, карточка үчүн оптималдашылат.',
    'employees.fullNameLabel': 'Аты-жөнү *',
    'employees.positionsLabel': 'Кызматтар * (бирөө же бир нечөө тандаңыз)',
    'employees.emailLabel': 'Email',
    'employees.phoneLabel': 'Телефон',
    'employees.experienceLabel': 'ОКУРМЭНдеги тажрыйба',
    'employees.educationLabel': 'Билими',
    'employees.bioLabel': 'Баяны / Сүрөттөмө',
    'employees.fullNamePlaceholder': 'Иван Иванов',
    'employees.emailPlaceholder': 'email@email.com',
    'employees.phonePlaceholder': '+996 XXX XXX XXX',
    'employees.experiencePlaceholder': '1 жыл 3 ай',
    'employees.educationPlaceholder': 'Жогорку билим',
    
    // Кызматтар
    'position.founder': 'Негиздөөчү',
    'position.director': 'Жетекчи/Директор',
    'position.headTeacher': 'Окуу бөлүмүнүн башчысы',
    'position.departmentHead': 'Бөлүм башчысы',
    'position.rop': 'РОП',
    'position.seniorManager': 'Улук менеджер',
    'position.manager': 'Менеджер',
    'position.curator': 'Куратор',
    'position.mentor': 'Ментор',
    'position.teacher': 'Мугалим',
    'position.developer': 'Иштеп чыгуучу',
    'position.hr': 'HR',
    'position.marketing': 'Маркетолог',
    'position.smm': 'SMM',
    'position.sales': 'Сатуу',
    'position.adminStaff': 'Административдик кызматкерлер',
    'position.other': 'Башка',
    
    // Бөлүмдөр
    'department.all': 'Бардык кызматкерлер',
    'department.leadership': 'Жетекчилик',
    'department.mentoring': 'Менторинг',
    'department.salesManagement': 'Сатуу жана Башкаруу',
    'department.studio': 'ОКУРМЭН Студия',
    
    // Окуучулар
    'students.title': 'Окуучулар жана Топтор',
    'students.totalInGroups': 'Жалпы: {total} окуучу {groups} топто',
    'students.createGroup': 'Топ түзүү',
    'students.noGroups': 'Топтор табылган жок',
    'students.group': 'Топ',
    'students.studentsCount': '{count} окуучу',
    'students.statusActive': 'Окуйт',
    'students.statusInactive': 'Активдүү эмес',
    'students.statusGraduated': 'Бүтүрдү',
    'students.statusDropped': 'Чыккан',
    'students.dateNotSpecified': 'Көрсөтүлгөн эмес',
    'students.startDate': 'Башталышы:',
    'students.endDate': 'Аяктоосу:',
    'students.editGroup': 'Топту өзгөртүү',
    'students.groupName': 'Топтун аталышы *',
    'students.mentor': 'Топтун ментору',
    'students.noMentor': '-- Ментор жок --',
    'students.groupActive': 'Топ активдүү',
    'students.addToGroup': 'Топко окуучу кошуу',
    'students.fullNameRequired': 'Окуучунун аты-жөнү *',
    'students.groupPrefix': 'Топ',
    'students.studentCount': '{count} окуучу',
    'students.confirmDeleteGroup': 'Топту "{name}" өчүрүүгө ишенесизби?',
    
    // Сабактар
    'lessons.title': 'Сабактар',
    'lessons.management': 'Курстардын сабактарын башкаруу',
    'lessons.addLesson': 'Сабак кошуу',
    'lessons.searchPlaceholder': 'Аталышы же сүрөттөмөсү боюнча издөө',
    'lessons.allCourses': 'Бардык курстар',
    'lessons.notFound': 'Сабактар табылган жок',
    'lessons.noTitle': 'Аталышы жок',
    'lessons.course': 'Курс:',
    'lessons.courseNotSpecified': 'Курс көрсөтүлгөн эмес',
    'lessons.noDescription': 'Сүрөттөмө жок',
    'lessons.video': 'Видео',
    'lessons.content': 'Мазмун',
    'lessons.editLesson': 'Сабакты өзгөртүү',
    'lessons.createLesson': 'Сабак түзүү',
    'lessons.selectCourse': 'Курс тандаңыз',
    'lessons.lessonTitle': 'Сабактын аталышы',
    'lessons.order': 'Тартиби',
    'lessons.videoUrl': 'Видео URL',
    'lessons.lessonContent': 'Сабактын мазмуну',
    'lessons.durationPlaceholder': '45 мүнөт',
    'lessons.videoUrlPlaceholder': 'https://youtube.com/...',
    'lessons.contentPlaceholder': 'Markdown сабактын мазмуну...',
    'lessons.confirmDelete': 'Бул сабакты өчүрүүгө ишенесизби?',
    
    // Бүтүрүүчүлөр
    'alumni.title': 'Бүтүрүүчүлөр',
    'alumni.subtitle': 'Окуучуларыбыздын ийгиликтүү окуялары',
    'alumni.addAlumni': 'Бүтүрүүчү кошуу',
    'alumni.searchPlaceholder': 'Аты, компаниясы же кызматы боюнча издөө',
    'alumni.notFound': 'Бүтүрүүчүлөр табылган жок',
    'alumni.projects': 'Долбоорлор:',
    'alumni.confirmDelete': 'Бул бүтүрүүчүнү өчүрүүгө ишенесизби?',
    
    // Арыздар
    'applications.title': 'Курстарга арыздар',
    'applications.subtitle': 'Окуучулардын арыздарын башкаруу',
    'applications.searchPlaceholder': 'Аты, email же телефону боюнча издөө',
    'applications.allStatuses': 'Бардык статустар',
    'applications.statusPending': 'Күтүүдө',
    'applications.statusContacted': 'Байланышты',
    'applications.statusConfirmed': 'Ырасталды',
    'applications.statusRejected': 'Четке кагылды',
    'applications.statusCancelled': 'Жокко чыгарылды',
    'applications.notFound': 'Арыздар табылган жок',
    'applications.noEmail': 'Email жок',
    'applications.noPhone': 'Телефон жок',
    'applications.course': 'Курс:',
    
    // Пикирлер
    'reviews.title': 'Пикирлер',
    'reviews.subtitle': 'Окуучулардын пикирлерин башкаруу',
    'reviews.searchPlaceholder': 'Аты, пикири же курсу боюнча издөө',
    'reviews.allStatuses': 'Бардык статустар',
    'reviews.statusPending': 'Модерацияда',
    'reviews.statusPublished': 'Жарыяланды',
    'reviews.statusRejected': 'Четке кагылды',
    'reviews.notFound': 'Пикирлер табылган жок',
    'reviews.anonymous': 'Аноним',
    'reviews.noEmail': 'Email жок',
    'reviews.noText': 'Пикир тексти жок',
    
    // Жөндөөлөр
    'settings.title': 'Жөндөөлөр',
    'settings.subtitle': 'Системанын жөндөөлөрүн башкаруу',
    'settings.general': 'Жалпы',
    'settings.profile': 'Профиль',
    'settings.notifications': 'Билдирүүлөр',
    'settings.security': 'Коопсуздук',
    'settings.theme': 'Тема',
    'settings.lightMode': 'Жарык режим',
    'settings.darkMode': 'Караңгы режим',
    'settings.changeTheme': 'Көрсөтүү темасын өзгөртүү',
    'settings.language': 'Тил',
    'settings.sectionInDevelopment': 'Бул бөлүм иштеп жатат',
    
    // Сайт статистикасы
    'siteStats.title': 'Сайт статистикасы',
    'siteStats.subtitle': 'Башкы бетте көрсөтүлгөн статистиканы башкаруу',
    'siteStats.totalStudents': 'Окуучулардын жалпы саны',
    'siteStats.displayedAs': 'Башкы бетте төмөнкүчө көрсөтүлөт:',
    'siteStats.employmentRate': 'Жумушка орношуу пайызы',
    
    // Сүрөт жүктөөчү
    'imageUploader.fileTooLarge': 'Файл өтө чоң! Максимум {maxSizeMB}MB',
    'imageUploader.pleaseSelectImage': 'Сүрөттү тандаңыз',
    'imageUploader.change': 'Өзгөртүү',
    'imageUploader.clickToSelect': 'Сүрөттү тандоо үчүн басыңыз',
    'imageUploader.square': 'Квадрат 1:1',
    'imageUploader.wide': 'Кең 16:9',
    'imageUploader.portrait': 'Портрет 3:4',
    'imageUploader.standard': 'Стандарт 4:3',
    'imageUploader.editImage': 'Сүрөттү өзгөртүү',
    'imageUploader.dragScale': 'Сүрөттү тартыңыз, масштабдаңыз жана буруңуз',
    'imageUploader.dragHint': '💡 Сүрөттү жылдыруу үчүн кармап тартыңыз',
    'imageUploader.rotate90': '90° бурууу',
    'imageUploader.reset': 'Баштапкы абалга келтирүү',
    
    // Каталар
    'error.updateApplicationStatus': 'Арыздын статусун жаңыртууда ката: {error}',
    'error.updateApplicationStatusGeneric': 'Арыздын статусун жаңыртууда ката',
    'error.apiConnection': 'APIге туташуу мүмкүн эмес. Интернет байланышты текшериңиз.',
    
    // Статистика баракчасы
    'statistics.title': 'Статистиканы башкаруу',
    'statistics.subtitle': 'Сайтта көрсөтүү үчүн мөөнөт жана көрсөткүчтөрдү жөндөңүз',
    'statistics.save': 'Сактоо',
    'statistics.saving': 'Сакталууда...',
    'statistics.saveSuccess': '✅ Жөндөөлөр сакталды',
    'statistics.saveError': '❌ Сактоодо ката',
    'statistics.siteStatsTitle': 'Башкы баракчанын статистикасы',
    'statistics.siteStatsDescription': 'Бул маалыматтар сайттын башкы бетинде көрсөтүлөт',
    'statistics.saveSiteStats': 'Сайт статистикасын сактоо',
    'statistics.savingSiteStats': 'Сакталууда...',
    'statistics.periodTitle': 'Мөөнөт',
    'statistics.periodType': 'Мөөнөттүн түрү',
    'statistics.periodMonth': 'Ай үчүн',
    'statistics.periodYear': 'Жыл үчүн',
    'statistics.periodAllTime': 'Бардык убакыт',
    'statistics.month': 'Ай',
    'statistics.year': 'Жыл',
    'statistics.publishTitle': 'Жарыялоо',
    'statistics.publishCheckbox': 'Сайтта статистиканы көрсөтүү',
    'statistics.metricsTitle': 'Мөөнөт көрсөткүчтөрү',
    'statistics.metricsDescription': 'Бул көрсөткүчтөр тандалган мөөнөт үчүн эсептелет',
    'statistics.currentMetricsTitle': 'Учурдагы көрсөткүчтөр',
    'statistics.currentMetricsDescription': 'Бул көрсөткүчтөр мөөнөткө көз каранды эмес',
    'statistics.metricValue': 'Маани: {value}',
    'statistics.monthJanuary': 'Январь',
    'statistics.monthFebruary': 'Февраль',
    'statistics.monthMarch': 'Март',
    'statistics.monthApril': 'Апрель',
    'statistics.monthMay': 'Май',
    'statistics.monthJune': 'Июнь',
    'statistics.monthJuly': 'Июль',
    'statistics.monthAugust': 'Август',
    'statistics.monthSeptember': 'Сентябрь',
    'statistics.monthOctober': 'Октябрь',
    'statistics.monthNovember': 'Ноябрь',
    'statistics.monthDecember': 'Декабрь',
    'statistics.metricNewStudents': 'Жаңы окуучулар',
    'statistics.metricNewStudentsDesc': 'Мөөнөттөгү жаңы окуучулардын саны',
    'statistics.metricNewApplications': 'Жаңы арыздар',
    'statistics.metricNewApplicationsDesc': 'Мөөнөттөгү жаңы арыздардын саны',
    'statistics.metricCompletedApplications': 'Аяктаган арыздар',
    'statistics.metricCompletedApplicationsDesc': 'Ырасталган арыздардын саны',
    'statistics.metricNewPayments': 'Жаңы төлөмдөр',
    'statistics.metricNewPaymentsDesc': 'Мөөнөттөгү жаңы төлөмдөрдүн саны',
    'statistics.metricTotalPaymentAmount': 'Төлөмдөр суммасы (сом)',
    'statistics.metricTotalPaymentAmountDesc': 'Мөөнөттөгү төлөмдөрдүн жалпы суммасы',
    'statistics.metricNewReviews': 'Жаңы пикирлер',
    'statistics.metricNewReviewsDesc': 'Жаңы пикирлердин саны',
    'statistics.metricNewBookings': 'Жаңы броньдар',
    'statistics.metricNewBookingsDesc': 'Жаңы броньдардын саны',
    'statistics.metricTotalStudents': 'Жалпы окуучулар',
    'statistics.metricTotalStudentsDesc': 'Учурдагы окуучулардын саны',
    'statistics.metricActiveStudents': 'Активдүү окуучулар',
    'statistics.metricActiveStudentsDesc': 'Активдүү окуучулардын саны',
    'statistics.metricTotalCourses': 'Жалпы курстар',
    'statistics.metricTotalCoursesDesc': 'Учурдагы курстардын саны',
    'statistics.metricActiveCourses': 'Активдүү курстар',
    'statistics.metricActiveCoursesDesc': 'Активдүү курстардын саны',
    'statistics.metricTotalEmployees': 'Жалпы кызматкерлер',
    'statistics.metricTotalEmployeesDesc': 'Учурдагы кызматкерлердин саны',
    'statistics.metricActiveEmployees': 'Активдүү кызматкерлер',
    'statistics.metricActiveEmployeesDesc': 'Активдүү кызматкерлердин саны',
    'statistics.metricTotalGroups': 'Жалпы топтор',
    'statistics.metricTotalGroupsDesc': 'Учурдагы топтордун саны',
    'statistics.metricTotalLessons': 'Жалпы сабактар',
    'statistics.metricTotalLessonsDesc': 'Учурдагы сабактардын саны',
    'statistics.metricTotalAlumni': 'Бүтүрүүчүлөр',
    'statistics.metricTotalAlumniDesc': 'Бүтүрүүчүлөрдүн саны',
    
    // Башкы панель
    'dashboard.totalCoursesLabel': 'Жалпы курстар',
    'dashboard.applicationsLabel': 'Арыздар',
    'dashboard.revenueLabel': 'Киреше',
    'dashboard.quickActionsTitle': 'Тез аракеттер',
    'dashboard.addCourseButton': 'Курс кошуу',
    'dashboard.addEmployeeButton': 'Кызматкер кошуу',
    'dashboard.viewApplicationsButton': 'Арыздарды көрүү',
    'dashboard.courseNotSpecified': 'Курс көрсөтүлгөн эмес',
    
    // Жүктөө жана каталар
    'common.loadingEllipsis': 'Жүктөлүүдө...',
    'error.loadingError': 'Жүктөөдө ката',
    'error.pleaseReload': 'Баракчаны кайра жүктөңүз',
    'common.reload': 'Кайра жүктөө',
    
    // Окуучулар билдирүүлөрү
    'students.errorLoadingGroups': '❌ Топторду жүктөөдө ката',
    'students.studentRemovedFromGroup': '✅ "{name}" топтон чыгарылды',
    'students.errorRemovingStudent': '❌ Окуучуну чыгаруудаката',
    'students.groupDeletedSuccess': '✅ Топ "{name}" ийгиликтүү өчүрүлдү',
    'students.errorDeletingGroup': '❌ Топту өчүрүүдө ката',
    'students.confirmDeleteStudent': '"{name}" топтон чыгарууга ишенесизби?',
    'students.confirmDeleteGroupMessage': '"{name}" топун өчүрүүгө ишенесизби?',
    'students.noGroupsFound': 'Топтор табылган жок',
    'students.noStudentsInGroup': 'Топто азырынча окуучулар жок',
    'students.addFirstStudent': 'Биринчи окуучуну кошуу',
    'students.editGroupTooltip': 'Топту өзгөртүү',
    'students.deleteGroupTooltip': 'Топту өчүрүү',
    'students.addStudentTooltip': 'Окуучу кошуу',
    'students.grantAccessTooltip': 'Курска кирүү укугун берүү',
    'students.grantAccessButton': 'Курска кирүү укугун берүү',
    'students.deleteStudentTooltip': 'Топтон чыгаруу',
    'students.editGroupTitle': 'Топту өзгөртүү {name}',
    'students.createGroupTitle': 'Топ түзүү',
    'students.groupNameLabel': 'Топтун аталышы *',
    'students.mentorLabel': 'Топтун ментору',
    'students.noMentorOption': '-- Ментор жок --',
    'students.mentorHint': 'Топ үчүн ментор тандаңыз (милдеттүү эмес)',
    'students.descriptionLabel': 'Сүрөттөмө',
    'students.descriptionPlaceholder': 'Топту сүрөттөп бериңиз...',
    'students.startDateLabel': 'Башталган датасы',
    'students.endDateLabel': 'Аяктаган датасы',
    'students.groupActiveLabel': 'Топ активдүү',
    'students.groupUpdatedSuccess': '✅ Топ "{name}" жаңыланды',
    'students.groupCreatedSuccess': '✅ Топ "{name}" түзүлдү',
    'students.saveErrorGeneric': 'Ката: Топту сактоо мүмкүн болгон жок',
    'students.loadingMentors': 'Менторлор жүктөлүүдө...',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ru');

  useEffect(() => {
    // Загружаем язык из localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ru', 'en', 'ky'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, any>): string => {
    const translationKey = key as keyof typeof translations['ru'];
    let text = (translations[language] as any)[key] || key;
    
    // Замена параметров {name} в строке
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), String(params[param]));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
